use chrono::Utc;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

use crate::error::AppResult;
use crate::models::{ShellType, Snippet};

/// Generate the output filename for a shell type
pub fn get_output_filename(shell: &ShellType) -> String {
    format!(
        ".snippets-manager-{}.{}",
        shell.as_str(),
        shell.file_extension()
    )
}

/// Generate file header comment
fn generate_header(shell: &ShellType, snippet_count: usize) -> String {
    let timestamp = Utc::now().format("%Y-%m-%d %H:%M:%S UTC");
    let comment_char = "#";

    format!(
        r#"{comment_char} ============================================================
{comment_char} Shell Snippets Manager - Auto-generated file
{comment_char} Shell: {shell}
{comment_char} Generated: {timestamp}
{comment_char} Snippets: {snippet_count}
{comment_char}
{comment_char} DO NOT EDIT THIS FILE DIRECTLY!
{comment_char} Changes will be overwritten by the Shell Snippets Manager.
{comment_char} ============================================================

"#,
        comment_char = comment_char,
        shell = shell.as_str(),
        timestamp = timestamp,
        snippet_count = snippet_count,
    )
}

/// Generate snippet block with header comment
fn generate_snippet_block(snippet: &Snippet, tags: &[String]) -> String {
    let comment_char = "#";

    let description_line = snippet
        .description
        .as_ref()
        .map(|d| format!("\n{} Description: {}", comment_char, d))
        .unwrap_or_default();

    let tags_line = if tags.is_empty() {
        String::new()
    } else {
        format!("\n{} Tags: {}", comment_char, tags.join(", "))
    };

    format!(
        r#"
{comment_char} --- [{id}] {name} ---{description}{tags}
{content}
"#,
        comment_char = comment_char,
        id = snippet.id,
        name = snippet.name,
        description = description_line,
        tags = tags_line,
        content = snippet.content,
    )
}

/// Snippet with its associated tags for sync
pub struct SnippetWithTags {
    pub snippet: Snippet,
    pub tags: Vec<String>,
}

/// Sync snippets to a shell-specific file
pub fn sync_to_file(
    snippets_with_tags: Vec<SnippetWithTags>,
    shell: ShellType,
    output_dir: PathBuf,
) -> AppResult<PathBuf> {
    // Ensure output directory exists
    fs::create_dir_all(&output_dir)?;

    let filename = get_output_filename(&shell);
    let output_path = output_dir.join(&filename);

    // Generate file content
    let mut content = generate_header(&shell, snippets_with_tags.len());

    for swt in &snippets_with_tags {
        content.push_str(&generate_snippet_block(&swt.snippet, &swt.tags));
    }

    // Add footer
    content.push_str(&format!(
        "\n# --- End of Shell Snippets Manager ({} snippets) ---\n",
        snippets_with_tags.len()
    ));

    // Write atomically (write to temp, then rename)
    let temp_path = output_path.with_extension("tmp");
    {
        let mut file = fs::File::create(&temp_path)?;
        file.write_all(content.as_bytes())?;
        file.sync_all()?;
    }
    fs::rename(&temp_path, &output_path)?;

    Ok(output_path)
}

/// Get the source line to add to shell rc file
pub fn get_source_line(shell: &ShellType, output_dir: &PathBuf) -> String {
    let filename = get_output_filename(shell);
    let file_path = output_dir.join(&filename);

    match shell {
        ShellType::Fish => format!("source \"{}\"", file_path.display()),
        ShellType::Powershell => format!(". \"{}\"", file_path.display()),
        _ => format!(
            "[ -f \"{}\" ] && source \"{}\"",
            file_path.display(),
            file_path.display()
        ),
    }
}
